from pydantic import BaseModel
from typing import Optional, List

# --- Request Models (Input) ---

class ScanRequest(BaseModel):
    """
    Represents the input payload required to initiate a supply chain risk scan.

    This model validates the JSON body sent to the POST /api/scan endpoint.

    Attributes:
        region (str): The target geographic location to monitor (e.g., "Taiwan", "Shenzhen").
                      This string is passed directly to the Watchtower Agent.
        user_id (Optional[str]): An identifier for the user initiating the request.
                                 Defaults to 'demo-user' for stateless demo purposes.
    """
    region: str
    user_id: Optional[str] = "demo-user"

# --- Response Models (Output) ---

class ScanResponse(BaseModel):
    """
    Represents the standardized output returned to the client after a scan completes.

    This model ensures the Frontend receives a consistent schema, regardless of
    variations in the underlying LLM's text output.

    Attributes:
        region (str): The geographic location that was analyzed.
        risk_level (str): A categorical classification of the risk (e.g., "CRITICAL", "LOW").
                          Used by the UI to determine badge colors (Red/Green).
        summary (str): The detailed natural language report generated by the Watchtower Agent.
                       May contain Markdown formatting.
        timestamp (str): The ISO 8601 formatted date and time when the scan was completed.
    """
    region: str
    risk_level: str  # e.g., "CRITICAL", "LOW"
    summary: str     # The full agent report
    timestamp: str

    class Config:
        """Schema example for OpenAPI documentation."""
        json_schema_extra = {
            "example": {
                "region": "Taiwan",
                "risk_level": "CRITICAL",
                "summary": "**RISK ALERT**: Earthquake detected. Logic-Core-CPUs are at critical low stock.",
                "timestamp": "2025-11-30T14:35:43.598235"
            }
        }